version: "1.0"

volumes:
  liquibase-data:

services:
  liquibase:
    container_name: liquibase-container
    image: liquibase/liquibase:4.25
    command: update
    environment:
      #LIQUIBASE_LIQUIBASE_SCHEMA_NAME: liquibase#use when you create schema for tracking liquibase changes
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog.xml
      LIQUIBASE_COMMAND_DRIVER: org.postgresql.Driver
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres-db:5432/postgres
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: postgrespass
      LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME: public 
      LIQUIBASE_SEARCH_PATH: /liquibase
    volumes:
      - ./config/changelog.xml:/liquibase/changelog.xml
      - ./scripts:/liquibase/scripts
      - liquibase-data:/liquibase
    networks:
      - liquibase-network

networks:
  liquibase-network:    
