version: "1.0"

volumes:
  postgres-data:

services:
  postgres-db:
    container_name: postgres-container
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - liquibase-network

networks:
  liquibase-network:
    
      