version: "1.0"

services:
  liquibase:
    container_name: liquibase-container
    image: liquibase/liquibase:4.25
    command: generate-changelog
    environment:
      LIQUIBASE_COMMAND_CHANGELOG_FILE: /liquibase/generate/changelog-generate.sql
      LIQUIBASE_COMMAND_DRIVER: org.postgresql.Driver
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres-db:5432/postgres
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: postgrespass
      LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME: public 
      LIQUIBASE_SEARCH_PATH: /liquibase
    volumes:
      - ./generate:/liquibase/generate
    networks:
      - liquibase-network
networks:
  liquibase-network:    
