-- liquibase formatted sql

-- changeset liquibase:1710012089330-1
CREATE TABLE "newtable1" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR NOT NULL);

-- changeset liquibase:1710012089330-2
CREATE TABLE "newtable2" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR NOT NULL, "description" VARCHAR NOT NULL);

