-- liquibase formatted sql

-- changeset liquibase:1710011359782-2
CREATE TABLE "newtable2" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR NOT NULL, "description" VARCHAR NOT NULL);

